apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: contosoair
  name: contosoair
  namespace: contosoair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosoair
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: contosoair
    spec:
      containers:
      - image: devxextensiontest.azurecr.io/contosoair
        name: contosoair
        ports:
        - containerPort: 3000
        resources: {}
status: {}
